const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("klartext", {
  ready: () => ipcRenderer.send("renderer-ready"),
  onPrepare: (cb) => ipcRenderer.on("prepare", (_e, settings) => cb(settings)),
  prepared: (result) => ipcRenderer.send("prepared", result),
  onStart: (cb) => ipcRenderer.on("start", (_e, settings) => cb(settings)),
  onStop: (cb) => ipcRenderer.on("stop", (_e, options) => cb(options || {})),
  onCancel: (cb) => ipcRenderer.on("cancel", () => cb()),
  onProcessingStart: (cb) => ipcRenderer.on("processing-start", () => cb()),
  onRefiningStart: (cb) => ipcRenderer.on("refining-start", () => cb()),
  onModelCommand: (cb) => ipcRenderer.on("model-command", (_e, command) => cb(command)),
  onWorkspaceLocalTranscribe: (cb) => ipcRenderer.on("workspace-local-transcribe", (_e, request) => cb(request)),
  onWorkspaceLocalCancel: (cb) => ipcRenderer.on("workspace-local-cancel", (_e, requestId) => cb(requestId)),
  workspaceLocalResult: (payload) => ipcRenderer.send("workspace-local-result", payload),
  workspaceLocalProgress: (payload) => ipcRenderer.send("workspace-local-progress", payload),
  onWorkspaceAudioSegments: (cb) => ipcRenderer.on("workspace-audio-segments", (_e, request) => cb(request)),
  workspaceAudioSegment: (payload) => ipcRenderer.send("workspace-audio-segment", payload),
  result: (payload) => ipcRenderer.send("result", payload),
  silence: () => ipcRenderer.send("recording-silence"),
  limit: () => ipcRenderer.send("recording-limit"),
  error: (message) => ipcRenderer.send("pill-error", message),
  modelStatus: (status) => ipcRenderer.send("model-status", status),
  saveApiKey: (provider, key) => ipcRenderer.send("save-api-key", { provider, key }),
  onApiKeyConfig: (cb) => ipcRenderer.on("api-key-config", (_event, config) => cb(config)),
  closeKeyWindow: () => ipcRenderer.send("close-key-window"),
  saveWakeModels: (models) => ipcRenderer.invoke("save-wake-models", models),
  closeWakeSetup: () => ipcRenderer.send("close-wake-setup"),
});
